# SPDX-License-Identifier: Apache-2.0
# Note (Akazaakane): Qualified on one 141 GB H200 with two same-GPU replicas;
# byte identity requires deterministic inference.

config_cls: Qwen3TTSPipelineConfig
name: qwen3tts
model_path: Qwen/Qwen3-TTS-12Hz-0.6B-Base
enable_deterministic_inference: true

runtime_overrides:
  tts_engine:
    server_args_overrides:
      attention_backend: triton
      max_total_tokens: 30000
      max_running_requests: 8
      max_queued_requests: 16
      cuda_graph_max_bs: 8
      cuda_graph_bs: [1, 2, 4, 8]
      torch_compile_max_bs: 8
